#!/usr/bin/env ruby

# Execute this script to run RSpec for the app.
# To run all specs, navigate to the application's root folder and execute
#   bin/start_rspec
# rspec_starter takes command line options and forwards unknown options to rspec
#   bin/start_rspec --no-prep-db spec/features
# See the help output for more advanced ways to run the script
#   bin/start_rspec --help

require "bundler/setup"
require "rspec_starter"

# The path to the application's root folder.
APP_ROOT = Pathname.new File.expand_path('../', __dir__)

# Tasks are run from the top down.
RspecStarter.start do
  task :verify_display_server
  task :remove_tmp_folder
  task :rebuild_rails_app_database
  task :start_rspec
end
